import Head from 'next/head'
import Stripe from 'stripe'

import Product from '../components/product'
import ImageTopper from '../components/imagetopper'

export default function Home({ prices }) {
  return (
    <>
      <Head>
        <title>eCanteen | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-100'>
        <ImageTopper 
        heading="Home"
        imagelarge="https://artas.com.au/media/ARTAS-Architects_tasmania_Parklands-High-School-003.jpg"
        imagesmall="https://artas.com.au/media/ARTAS-Architects_tasmania_Parklands-High-School-003.jpg"
        />
        <section className='mb-8'>
          <div className='flex justify-center'>
            <div className='grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-8 list-none'>
              {prices.map((price) => 
                <li key={price.id}>
                  <Product
                  name={price.product.name}
                  price={price.unit_amount}
                  image={price.product.images[0]}
                  id={price.id}
                  />
                </li>
              )}
            </div>
          </div>
        </section>
        <section>

        </section>
      </div>
    </>
  )
}

export async function getServerSideProps() {
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
    apiVersion: "2020-08-27"
  });

  const prices = await stripe.prices.list({
    active: true,
    expand: ["data.product"],
  })

  console.log(prices.data)

  return {props: {prices: prices.data } };
}
