import Head from 'next/head'
import Stripe from 'stripe'

import Product from '../components/product'
import ImageTopper from '../components/imagetopper'

export default function Home({ prices }) {
  return (
    <>
      <Head>
        <title>eCanteen | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-100 h-screen'>
        <ImageTopper 
        heading="Home"
        imagelarge="https://artas.com.au/media/ARTAS-Architects_tasmania_Parklands-High-School-003.jpg"
        imagesmall="https://artas.com.au/media/ARTAS-Architects_tasmania_Parklands-High-School-003.jpg"
        />
        <section className='mb-8'>
          
        </section>
      </div>
    </>
  )
}